services:
  petstore:
    image: swaggerapi/petstore
    container_name: petstore
    # (optioneel) ook via HTTP direct testen:
    ports:
      - "8080:8080"
    networks: [appnet]

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - petstore            # niet wachten op 'healthy'
    ports:
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [appnet]

volumes:
  caddy_data:
  caddy_config:

networks:
  appnet:
    name: appnet
